import { useState } from "react";
import { useMutation } from "convex/react";
import { Activity, ArchiveRestore, CheckCircle2, DatabaseBackup, ServerCrash, TimerReset } from "lucide-react";
import type { Doc } from "../../convex/_generated/dataModel";
import { api } from "../../convex/_generated/api";

export function OperationsReadinessPanel({ workspace, jobs, backups, restoreDrills }: { workspace: Doc<"workspaces">; jobs: Doc<"executionJobs">[]; backups: Doc<"backupSnapshots">[]; restoreDrills: Doc<"restoreDrills">[] }) {
  const requestBackup = useMutation(api.operations.requestBackup);
  const requestRestore = useMutation(api.operations.requestRestoreDrill);
  const [objectRef, setObjectRef] = useState(`s3://agent-oven-backups/${workspace.slug}/snapshot.json.enc`);
  const [target, setTarget] = useState("ephemeral-restore-drill");
  const [notice, setNotice] = useState<string | null>(null);
  const latestBackup = backups[0];
  const latestDrill = restoreDrills[0];
  const failed = jobs.filter((job) => job.status === "failed").length;
  const terminal = jobs.filter((job) => ["succeeded", "failed", "canceled"].includes(job.status)).length;

  return <section className="operations-readiness surface operation-card" aria-labelledby="readiness-title"><header className="surface-header"><div><p className="kicker">Production operations</p><h2 id="readiness-title">Measure recovery, don’t promise it.</h2></div><Activity size={22} /></header><div className="readiness-metrics"><span><b>{jobs.filter((job) => job.status === "queued").length}</b><small>Queued jobs</small></span><span><b>{terminal ? Math.round((failed / terminal) * 100) : 0}%</b><small>Failure rate</small></span><span><b>{latestBackup?.state ?? "missing"}</b><small>Latest backup</small></span><span><b>{latestDrill?.state ?? "missing"}</b><small>Restore drill</small></span></div><div className="recovery-grid"><article><DatabaseBackup size={20} /><div><strong>Encrypted backup export</strong><p>Worker writes the tenant snapshot to your approved object-store reference and returns only a count and manifest digest.</p></div><label>Object reference<input value={objectRef} onChange={(event) => setObjectRef(event.target.value)} /></label><button className="button secondary" onClick={() => void requestBackup({ workspaceId: workspace._id, objectRef }).then(() => setNotice("Backup export requested. It remains unverified until the trusted worker completes the manifest."))}>Request backup</button></article><article><ArchiveRestore size={20} /><div><strong>Isolated restore drill</strong><p>Restores only into an ephemeral or staging target, then verifies row counts, receipt lineage, tenant isolation, RTO, and RPO.</p></div><label>Isolated target<input value={target} onChange={(event) => setTarget(event.target.value)} /></label><button className="button secondary" disabled={!latestBackup || latestBackup.state !== "completed"} onClick={() => latestBackup && void requestRestore({ snapshotId: latestBackup._id, targetEnvironment: target }).then(() => setNotice("Restore drill requested. A worker must report measured checks before it can pass."))}>Request restore drill</button></article></div><div className="recovery-proof"><span className={latestBackup?.state === "completed" ? "pass" : "pending"}>{latestBackup?.state === "completed" ? <CheckCircle2 size={14} /> : <DatabaseBackup size={14} />} Backup {latestBackup?.state ?? "not run"}</span><span className={latestDrill?.state === "passed" ? "pass" : "pending"}>{latestDrill?.state === "passed" ? <CheckCircle2 size={14} /> : <TimerReset size={14} />} Restore {latestDrill?.state ?? "not run"}</span>{latestDrill?.rtoSeconds !== undefined && <span className="pass"><TimerReset size={14} /> RTO {latestDrill.rtoSeconds}s · RPO {latestDrill.rpoSeconds}s</span>}</div>{notice && <p className="knowledge-notice" role="status">{notice}</p>}<p className="operations-caveat"><ServerCrash size={14} /> Workflow readiness is not storage activation. Production backup remains blocked until an object-store worker and credentials are deployed.</p></section>;
}
