import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const providerProfile = v.union(
  v.literal("economy"),
  v.literal("balanced"),
  v.literal("highest-quality"),
);

const authorityMode = v.union(
  v.literal("read-only"),
  v.literal("propose"),
  v.literal("approval-required"),
);

export default defineSchema({
  workspaces: defineTable({
    organizationId: v.optional(v.id("organizations")),
    slug: v.string(),
    name: v.string(),
    plan: v.union(v.literal("local"), v.literal("pilot"), v.literal("business")),
    createdAt: v.number(),
  }).index("by_slug", ["slug"]),

  agentSpecs: defineTable({
    workspaceId: v.id("workspaces"),
    name: v.string(),
    repository: v.string(),
    providerProfile,
    memoryMode: v.union(v.literal("run-only"), v.literal("architecture-history")),
    authorityMode,
    hardBudgetCents: v.number(),
    validators: v.array(v.string()),
    version: v.number(),
    status: v.union(v.literal("draft"), v.literal("active"), v.literal("suspended"), v.literal("revoked")),
    updatedAt: v.number(),
  })
    .index("by_workspace", ["workspaceId"])
    .index("by_workspace_status", ["workspaceId", "status"]),

  agentBlueprints: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    templateId: v.string(),
    name: v.string(),
    mode: v.union(v.literal("guided"), v.literal("architect")),
    triggerKind: v.union(v.literal("manual"), v.literal("schedule"), v.literal("webhook"), v.literal("event")),
    triggerLabel: v.string(),
    steps: v.array(v.object({ id: v.string(), label: v.string(), kind: v.union(v.literal("retrieve"), v.literal("reason"), v.literal("act"), v.literal("validate"), v.literal("notify")), connectorProvider: v.optional(v.string()), humanGate: v.boolean(), flow: v.optional(v.union(v.literal("sequential"), v.literal("parallel"), v.literal("branch"), v.literal("loop"))), dependsOn: v.optional(v.array(v.string())), conditionRef: v.optional(v.string()), maxIterations: v.optional(v.number()) })),
    memoryPolicy: v.union(v.literal("none"), v.literal("run-only"), v.literal("governed")),
    modelPolicy: v.union(v.literal("economy"), v.literal("balanced"), v.literal("highest-quality"), v.literal("auto")),
    authorityPolicy: v.union(v.literal("read-only"), v.literal("propose"), v.literal("approval-required")),
    evidenceLevel: v.union(v.literal("essential"), v.literal("full")),
    runtimeEngine: v.optional(v.union(v.literal("agent-oven-native"), v.literal("langgraph"), v.literal("mastra"))),
    inferenceAccess: v.optional(v.union(v.literal("agent-oven-api"), v.literal("byok"))),
    hardBudgetCents: v.number(),
    estimatedPlatformCredits: v.number(),
    version: v.number(),
    status: v.union(v.literal("draft"), v.literal("active"), v.literal("suspended")),
    updatedAt: v.number(),
  }).index("by_agent", ["agentSpecId"]),

  agentBlueprintVersions: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    blueprintId: v.id("agentBlueprints"),
    version: v.number(),
    canonical: v.string(),
    digest: v.string(),
    estimatedPlatformCredits: v.number(),
    runtimeEngine: v.optional(v.union(v.literal("agent-oven-native"), v.literal("langgraph"), v.literal("mastra"))),
    inferenceAccess: v.optional(v.union(v.literal("agent-oven-api"), v.literal("byok"))),
    createdAt: v.number(),
  }).index("by_blueprint_version", ["blueprintId", "version"]),

  agentCompositionDrafts: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    title: v.string(),
    intentDigest: v.string(),
    compilerDigest: v.string(),
    selectedRuntime: v.union(v.literal("agent-oven-native"), v.literal("langgraph"), v.literal("mastra")),
    runtimeRationale: v.string(),
    inferenceAccess: v.union(v.literal("agent-oven-api"), v.literal("byok")),
    authorityPolicy: v.union(v.literal("propose"), v.literal("approval-required")),
    memoryPolicy: v.union(v.literal("run-only"), v.literal("governed")),
    steps: v.array(v.object({ id: v.string(), label: v.string(), kind: v.union(v.literal("retrieve"), v.literal("reason"), v.literal("act"), v.literal("validate"), v.literal("notify")), humanGate: v.boolean(), flow: v.union(v.literal("sequential"), v.literal("parallel"), v.literal("branch"), v.literal("loop")), dependsOn: v.array(v.string()), maxIterations: v.optional(v.number()) })),
    evidenceChecks: v.array(v.string()),
    clarificationQuestions: v.array(v.string()),
    status: v.union(v.literal("needs-clarification"), v.literal("ready"), v.literal("applied")),
    createdBy: v.string(),
    createdAt: v.number(),
    appliedBlueprintId: v.optional(v.id("agentBlueprints")),
    appliedAt: v.optional(v.number()),
  })
    .index("by_agent_created", ["agentSpecId", "createdAt"])
    .index("by_workspace_status", ["workspaceId", "status"]),

  agentSpecVersions: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    version: v.number(),
    name: v.string(),
    repository: v.string(),
    providerProfile,
    memoryMode: v.union(v.literal("run-only"), v.literal("architecture-history")),
    authorityMode,
    hardBudgetCents: v.number(),
    validators: v.array(v.string()),
    digest: v.string(),
    source: v.union(v.literal("seed"), v.literal("save"), v.literal("import"), v.literal("rollback")),
    restoredFromVersion: v.optional(v.number()),
    createdAt: v.number(),
  })
    .index("by_agent_version", ["agentSpecId", "version"])
    .index("by_workspace_created", ["workspaceId", "createdAt"]),

  providerConnections: defineTable({
    workspaceId: v.id("workspaces"),
    provider: v.union(v.literal("openai"), v.literal("anthropic")),
    label: v.string(),
    secretRef: v.string(),
    status: v.union(v.literal("enabled"), v.literal("disabled")),
    updatedAt: v.number(),
  }).index("by_workspace_provider", ["workspaceId", "provider"]),

  providerRoutes: defineTable({
    workspaceId: v.id("workspaces"),
    profile: providerProfile,
    primaryProvider: v.string(),
    primaryModel: v.string(),
    fallbackProvider: v.string(),
    fallbackModel: v.string(),
    cacheAffinity: v.boolean(),
    updatedAt: v.number(),
  }).index("by_workspace_profile", ["workspaceId", "profile"]),

  runs: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    branch: v.string(),
    commitSha: v.string(),
    status: v.union(
      v.literal("awaiting-approval"),
      v.literal("approved"),
      v.literal("rejected"),
      v.literal("blocked"),
    ),
    estimatedCostCents: v.number(),
    actualCostCents: v.number(),
    proposedAction: v.string(),
    actionDigest: v.string(),
    startedAt: v.number(),
    completedAt: v.optional(v.number()),
  })
    .index("by_workspace_started", ["workspaceId", "startedAt"])
    .index("by_agent_started", ["agentSpecId", "startedAt"]),

  gates: defineTable({
    workspaceId: v.id("workspaces"),
    runId: v.id("runs"),
    order: v.number(),
    name: v.string(),
    kind: v.union(v.literal("deterministic"), v.literal("model")),
    status: v.union(v.literal("passed"), v.literal("warning"), v.literal("blocked")),
    evidenceClass: v.union(v.literal("proof-bearing"), v.literal("heuristic")),
    durationMs: v.number(),
    summary: v.string(),
  }).index("by_run_order", ["runId", "order"]),

  approvals: defineTable({
    workspaceId: v.id("workspaces"),
    runId: v.id("runs"),
    actionDigest: v.string(),
    proposedAction: v.string(),
    status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected")),
    requestedBy: v.string(),
    requestedAt: v.number(),
    decidedBy: v.optional(v.string()),
    decidedAt: v.optional(v.number()),
    rationale: v.optional(v.string()),
  })
    .index("by_run", ["runId"])
    .index("by_workspace_status", ["workspaceId", "status"]),

  adversarialApprovalReviews: defineTable({
    workspaceId: v.id("workspaces"),
    runId: v.id("runs"),
    approvalId: v.id("approvals"),
    actionDigest: v.string(),
    actionClass: v.union(v.literal("read"), v.literal("analyze"), v.literal("draft"), v.literal("code-change"), v.literal("external-send"), v.literal("deploy"), v.literal("delete"), v.literal("payment"), v.literal("credential")),
    environment: v.union(v.literal("test"), v.literal("production")),
    approvalAgentId: v.string(),
    verdict: v.union(v.literal("auto-approved"), v.literal("human-required"), v.literal("denied")),
    reasonCodes: v.array(v.string()),
    checks: v.array(v.object({ id: v.string(), passed: v.boolean(), evidence: v.string() })),
    evidenceDigests: v.array(v.string()),
    evidenceDigest: v.string(),
    proofDelta: v.object({
      reusedEvidence: v.array(v.string()),
      newEvidence: v.array(v.string()),
      missingEvidence: v.array(v.string()),
      reviewScope: v.union(v.literal("full"), v.literal("focused")),
    }),
    policyVersion: v.literal("adversarial-approval.v1"),
    expiresAt: v.number(),
    createdAt: v.number(),
  })
    .index("by_approval", ["approvalId"])
    .index("by_run", ["runId"])
    .index("by_workspace_created", ["workspaceId", "createdAt"]),

  receipts: defineTable({
    workspaceId: v.id("workspaces"),
    runId: v.optional(v.id("runs")),
    memoryId: v.optional(v.id("memories")),
    costReservationId: v.optional(v.id("costReservations")),
    capabilityGrantId: v.optional(v.id("capabilityGrants")),
    workspaceMembershipId: v.optional(v.id("workspaceMemberships")),
    agentSpecId: v.optional(v.id("agentSpecs")),
    outcomeContractId: v.optional(v.id("outcomeContracts")),
    type: v.union(v.literal("run"), v.literal("approval"), v.literal("memory-deletion"), v.literal("memory-correction"), v.literal("agent-lifecycle"), v.literal("release-safety"), v.literal("incident-response"), v.literal("budget-control"), v.literal("trust-decision"), v.literal("identity-access"), v.literal("agent-blueprint"), v.literal("platform-credit"), v.literal("outcome-exchange")),
    event: v.string(),
    fingerprint: v.string(),
    previousFingerprint: v.optional(v.string()),
    signatureState: v.literal("unsigned"),
    createdAt: v.number(),
  })
    .index("by_workspace_created", ["workspaceId", "createdAt"])
    .index("by_run_created", ["runId", "createdAt"]),

  memories: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    subject: v.string(),
    content: v.string(),
    source: v.string(),
    purpose: v.string(),
    provenance: v.string(),
    confidence: v.number(),
    retentionDays: v.number(),
    trustLabel: v.literal("untrusted-context"),
    policyVersion: v.optional(v.literal("memory-policy.v1")),
    safetyState: v.optional(v.union(v.literal("eligible"), v.literal("quarantined"))),
    safetyReason: v.optional(v.string()),
    supersedesMemoryId: v.optional(v.id("memories")),
    supersededAt: v.optional(v.number()),
    supersededByMemoryId: v.optional(v.id("memories")),
    deletionReason: v.optional(v.string()),
    createdAt: v.number(),
    deletedAt: v.optional(v.number()),
  })
    .index("by_workspace_agent", ["workspaceId", "agentSpecId"])
    .index("by_workspace_deleted", ["workspaceId", "deletedAt"]),

  usageRecords: defineTable({
    workspaceId: v.id("workspaces"),
    runId: v.id("runs"),
    estimatedCostCents: v.number(),
    actualCostCents: v.number(),
    createdAt: v.number(),
  }).index("by_run", ["runId"]),

  costReservations: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    runId: v.id("runs"),
    callKey: v.string(),
    provider: v.string(),
    model: v.string(),
    estimatedCostCents: v.number(),
    actualCostCents: v.optional(v.number()),
    state: v.union(v.literal("reserved"), v.literal("settled"), v.literal("released")),
    createdAt: v.number(),
    completedAt: v.optional(v.number()),
  })
    .index("by_run_call", ["runId", "callKey"])
    .index("by_run_state", ["runId", "state"]),

  capabilityGrants: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    runId: v.id("runs"),
    subject: v.string(),
    audience: v.string(),
    scope: v.string(),
    resource: v.string(),
    environment: v.union(v.literal("test"), v.literal("production")),
    risk: v.union(v.literal("low"), v.literal("moderate"), v.literal("high")),
    policyVersion: v.literal("trust-policy.v1"),
    actionDigest: v.string(),
    maxCostCents: v.number(),
    expiresAt: v.number(),
    state: v.union(v.literal("active"), v.literal("consumed"), v.literal("revoked")),
    issuedBy: v.string(),
    createdAt: v.number(),
    consumedAt: v.optional(v.number()),
    revokedAt: v.optional(v.number()),
    revocationReason: v.optional(v.string()),
  })
    .index("by_run_state", ["runId", "state"])
    .index("by_agent_state", ["agentSpecId", "state"]),

  trustDecisions: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    runId: v.id("runs"),
    capabilityGrantId: v.id("capabilityGrants"),
    requestKey: v.string(),
    decision: v.literal("allow"),
    reasonCode: v.literal("CAPABILITY_AUTHORIZED"),
    requestDigest: v.string(),
    policyVersion: v.literal("trust-policy.v1"),
    costReservationId: v.id("costReservations"),
    createdAt: v.number(),
  })
    .index("by_run_created", ["runId", "createdAt"])
    .index("by_grant", ["capabilityGrantId"]),

  workspaceMemberships: defineTable({
    workspaceId: v.id("workspaces"),
    tokenIdentifier: v.string(),
    memberLabel: v.string(),
    role: v.union(v.literal("owner"), v.literal("admin"), v.literal("operator"), v.literal("reviewer"), v.literal("viewer")),
    status: v.union(v.literal("active"), v.literal("revoked")),
    createdBy: v.string(),
    directoryExternalId: v.optional(v.string()),
    createdAt: v.number(),
    revokedAt: v.optional(v.number()),
    revocationReason: v.optional(v.string()),
  })
    .index("by_workspace_subject", ["workspaceId", "tokenIdentifier"])
    .index("by_subject_status", ["tokenIdentifier", "status"])
    .index("by_workspace_status", ["workspaceId", "status"]),

  organizations: defineTable({
    slug: v.string(),
    name: v.string(),
    status: v.union(v.literal("active"), v.literal("suspended")),
    createdAt: v.number(),
  }).index("by_slug", ["slug"]),

  organizationMemberships: defineTable({
    organizationId: v.id("organizations"),
    tokenIdentifier: v.string(),
    memberLabel: v.string(),
    role: v.union(v.literal("owner"), v.literal("admin"), v.literal("auditor")),
    status: v.union(v.literal("active"), v.literal("suspended")),
    createdAt: v.number(),
    suspendedAt: v.optional(v.number()),
  })
    .index("by_org_subject", ["organizationId", "tokenIdentifier"])
    .index("by_subject_status", ["tokenIdentifier", "status"]),

  directoryConnections: defineTable({
    organizationId: v.id("organizations"),
    protocol: v.union(v.literal("scim-2.0"), v.literal("oidc"), v.literal("saml-2.0")),
    issuer: v.string(),
    tenantKey: v.string(),
    secretRef: v.string(),
    defaultWorkspaceRole: v.union(v.literal("admin"), v.literal("operator"), v.literal("reviewer"), v.literal("viewer")),
    status: v.union(v.literal("setup-required"), v.literal("active"), v.literal("disabled")),
    updatedAt: v.number(),
  }).index("by_org_protocol", ["organizationId", "protocol"]),

  directoryProvisioningEvents: defineTable({
    organizationId: v.id("organizations"),
    directoryConnectionId: v.id("directoryConnections"),
    workspaceId: v.id("workspaces"),
    externalId: v.string(),
    operation: v.union(v.literal("provision"), v.literal("update"), v.literal("suspend")),
    membershipId: v.id("workspaceMemberships"),
    actor: v.string(),
    createdAt: v.number(),
  })
    .index("by_connection_external", ["directoryConnectionId", "externalId"])
    .index("by_org_created", ["organizationId", "createdAt"]),

  enterprisePolicies: defineTable({
    organizationId: v.id("organizations"),
    workspaceId: v.id("workspaces"),
    residencyRegion: v.string(),
    backupRegion: v.string(),
    kmsKeyRef: v.string(),
    retentionDays: v.number(),
    rtoMinutes: v.number(),
    rpoMinutes: v.number(),
    status: v.union(v.literal("draft"), v.literal("enforced")),
    updatedAt: v.number(),
  }).index("by_workspace", ["workspaceId"]),

  legalHolds: defineTable({
    organizationId: v.id("organizations"),
    workspaceId: v.id("workspaces"),
    scope: v.union(v.literal("workspace"), v.literal("agent"), v.literal("subject")),
    scopeKey: v.string(),
    reason: v.string(),
    status: v.union(v.literal("active"), v.literal("released")),
    placedBy: v.string(),
    placedAt: v.number(),
    releasedBy: v.optional(v.string()),
    releasedAt: v.optional(v.number()),
  })
    .index("by_workspace_status", ["workspaceId", "status"])
    .index("by_workspace_scope", ["workspaceId", "scope", "scopeKey"]),

  deletionRequests: defineTable({
    organizationId: v.id("organizations"),
    workspaceId: v.id("workspaces"),
    scope: v.union(v.literal("workspace"), v.literal("agent"), v.literal("subject")),
    scopeKey: v.string(),
    reason: v.string(),
    status: v.union(v.literal("blocked-by-legal-hold"), v.literal("approved-for-execution"), v.literal("completed")),
    requestedBy: v.string(),
    requestedAt: v.number(),
    completedAt: v.optional(v.number()),
  }).index("by_workspace_requested", ["workspaceId", "requestedAt"]),

  admissionPolicies: defineTable({
    organizationId: v.id("organizations"),
    workspaceId: v.id("workspaces"),
    route: v.string(),
    maxRequests: v.number(),
    windowSeconds: v.number(),
    maxConcurrentRuns: v.number(),
    status: v.union(v.literal("monitor"), v.literal("enforced")),
    updatedAt: v.number(),
  }).index("by_workspace_route", ["workspaceId", "route"]),

  admissionWindows: defineTable({
    workspaceId: v.id("workspaces"),
    route: v.string(),
    windowStart: v.number(),
    count: v.number(),
    updatedAt: v.number(),
  }).index("by_workspace_route", ["workspaceId", "route"]),

  conciergeProfiles: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    serviceName: v.string(),
    serviceArea: v.string(),
    appointmentDurationMinutes: v.number(),
    minimumLeadScore: v.number(),
    modeledJobValueCents: v.number(),
    approvalRequired: v.literal(true),
    version: v.number(),
    status: v.union(v.literal("draft"), v.literal("sandbox-ready"), v.literal("production-ready")),
    updatedAt: v.number(),
  }).index("by_agent", ["agentSpecId"]),

  conciergeAdapters: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    kind: v.union(v.literal("calendar"), v.literal("messaging"), v.literal("billing"), v.literal("model")),
    provider: v.string(),
    accountLabel: v.string(),
    secretRef: v.optional(v.string()),
    status: v.union(v.literal("setup-required"), v.literal("active"), v.literal("disabled")),
    validationDigest: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_agent_kind", ["agentSpecId", "kind"]),

  conciergeLeads: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    leadAlias: v.string(),
    serviceRequested: v.string(),
    areaLabel: v.string(),
    serviceMatch: v.boolean(),
    areaMatch: v.boolean(),
    urgency: v.union(v.literal("flexible"), v.literal("soon"), v.literal("urgent")),
    contactReady: v.boolean(),
    contactConsent: v.literal(true),
    score: v.number(),
    classification: v.union(v.literal("qualified"), v.literal("needs-review"), v.literal("rejected")),
    decisionReasons: v.array(v.string()),
    status: v.union(v.literal("new"), v.literal("awaiting-approval"), v.literal("booked"), v.literal("closed")),
    createdAt: v.number(),
  }).index("by_agent_created", ["agentSpecId", "createdAt"]),

  conciergeBookingApprovals: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    leadId: v.id("conciergeLeads"),
    environment: v.union(v.literal("sandbox"), v.literal("production")),
    proposedStartAt: v.number(),
    slotDigest: v.string(),
    status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected")),
    requestedAt: v.number(),
    decidedAt: v.optional(v.number()),
  }).index("by_lead", ["leadId"]),

  conciergeBookings: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    leadId: v.id("conciergeLeads"),
    approvalId: v.id("conciergeBookingApprovals"),
    environment: v.union(v.literal("sandbox"), v.literal("production")),
    startAt: v.number(),
    durationMinutes: v.number(),
    modeledValueCents: v.number(),
    status: v.union(v.literal("confirmed"), v.literal("attended"), v.literal("no-show"), v.literal("canceled")),
    createdAt: v.number(),
  }).index("by_agent_created", ["agentSpecId", "createdAt"]),

  conciergeOutcomeEvents: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    leadId: v.id("conciergeLeads"),
    bookingId: v.optional(v.id("conciergeBookings")),
    type: v.union(v.literal("lead-qualified"), v.literal("booking-confirmed"), v.literal("attended"), v.literal("no-show"), v.literal("canceled"), v.literal("revenue-confirmed")),
    evidenceClass: v.union(v.literal("modeled"), v.literal("observed")),
    valueCents: v.optional(v.number()),
    source: v.string(),
    createdAt: v.number(),
  }).index("by_agent_created", ["agentSpecId", "createdAt"]),

  knowledgeConnectors: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    provider: v.union(v.literal("google-drive"), v.literal("onedrive"), v.literal("sharepoint"), v.literal("notion"), v.literal("dropbox"), v.literal("confluence"), v.literal("web"), v.literal("s3"), v.literal("azure-blob"), v.literal("github"), v.literal("database")),
    label: v.string(),
    sourceLocator: v.string(),
    secretRef: v.optional(v.string()),
    syncMode: v.union(v.literal("manual"), v.literal("daily"), v.literal("weekly")),
    status: v.union(v.literal("setup-required"), v.literal("ready"), v.literal("disabled")),
    updatedAt: v.number(),
  })
    .index("by_agent_provider", ["agentSpecId", "provider"])
    .index("by_workspace_status", ["workspaceId", "status"]),

  authoritativeSources: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    sourceKey: v.string(),
    label: v.string(),
    jurisdiction: v.string(),
    publisher: v.string(),
    sourceGroup: v.string(),
    authorityCategory: v.union(v.literal("primary-law"), v.literal("official-regulator"), v.literal("official-registry"), v.literal("licensed-system-of-record"), v.literal("secondary-corroboration")),
    sourceRole: v.union(v.literal("primary"), v.literal("fallback"), v.literal("corroboration")),
    canonicalLocator: v.string(),
    endpointRef: v.optional(v.string()),
    licenseRef: v.optional(v.string()),
    freshnessSloSeconds: v.number(),
    maximumAgeSeconds: v.number(),
    minimumAuthoritativeSources: v.number(),
    requiredForRuns: v.boolean(),
    configDigest: v.string(),
    status: v.union(v.literal("setup-required"), v.literal("ready"), v.literal("disabled")),
    lastObservedAt: v.optional(v.number()),
    lastSuccessfulAt: v.optional(v.number()),
    lastContentDigest: v.optional(v.string()),
    consecutiveFailures: v.number(),
    updatedAt: v.number(),
  })
    .index("by_agent_key", ["agentSpecId", "sourceKey"])
    .index("by_agent_group", ["agentSpecId", "sourceGroup"])
    .index("by_workspace_status", ["workspaceId", "status"]),

  sourceObservations: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    sourceId: v.id("authoritativeSources"),
    observationKey: v.string(),
    outcome: v.union(v.literal("success"), v.literal("failure")),
    observedAt: v.number(),
    latencyMs: v.number(),
    sourcePublishedAt: v.optional(v.number()),
    contentDigest: v.optional(v.string()),
    failureCode: v.optional(v.union(v.literal("timeout"), v.literal("authentication"), v.literal("authorization"), v.literal("rate-limited"), v.literal("upstream-unavailable"), v.literal("invalid-response"), v.literal("license-unavailable"), v.literal("unknown"))),
    createdAt: v.number(),
  })
    .index("by_source_key", ["sourceId", "observationKey"])
    .index("by_source_observed", ["sourceId", "observedAt"]),

  creditAccounts: defineTable({
    workspaceId: v.id("workspaces"),
    plan: v.union(v.literal("starter"), v.literal("growth"), v.literal("business"), v.literal("enterprise")),
    availableCredits: v.number(),
    reservedCredits: v.number(),
    spentCredits: v.number(),
    monthlyAllocation: v.number(),
    periodStart: v.number(),
    periodEnd: v.number(),
    status: v.union(v.literal("active"), v.literal("past-due"), v.literal("suspended")),
    updatedAt: v.number(),
  }).index("by_workspace", ["workspaceId"]),

  creditReservations: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    blueprintId: v.id("agentBlueprints"),
    idempotencyKey: v.string(),
    quotedCredits: v.number(),
    actualCredits: v.optional(v.number()),
    state: v.union(v.literal("reserved"), v.literal("settled"), v.literal("released")),
    createdAt: v.number(),
    completedAt: v.optional(v.number()),
  })
    .index("by_workspace_key", ["workspaceId", "idempotencyKey"])
    .index("by_workspace_state", ["workspaceId", "state"]),

  creditTransactions: defineTable({
    workspaceId: v.id("workspaces"),
    reservationId: v.optional(v.id("creditReservations")),
    outcomeContractId: v.optional(v.id("outcomeContracts")),
    kind: v.union(v.literal("allocation"), v.literal("top-up"), v.literal("reserve"), v.literal("settle"), v.literal("release")),
    credits: v.number(),
    availableAfter: v.number(),
    reservedAfter: v.number(),
    reference: v.string(),
    createdAt: v.number(),
  }).index("by_workspace_created", ["workspaceId", "createdAt"]),

  outcomeContracts: defineTable({
    workspaceId: v.id("workspaces"),
    offerId: v.string(),
    offerVersion: v.literal(1),
    offerName: v.string(),
    outcome: v.string(),
    authority: v.string(),
    resultCredits: v.number(),
    evidenceCheckIds: v.array(v.string()),
    callerKind: v.union(v.literal("human"), v.literal("agent")),
    callerAgentId: v.optional(v.string()),
    callerSubject: v.string(),
    intentRef: v.string(),
    intentDigest: v.string(),
    mandateDigest: v.optional(v.string()),
    delegationDepth: v.number(),
    idempotencyKey: v.string(),
    contractDigest: v.string(),
    state: v.union(v.literal("accepted"), v.literal("running"), v.literal("evidence-submitted"), v.literal("verified"), v.literal("paid"), v.literal("disputed"), v.literal("canceled")),
    paymentRail: v.literal("platform-credits"),
    paymentState: v.union(v.literal("reserved"), v.literal("settled"), v.literal("released")),
    submitterSubject: v.optional(v.string()),
    evidenceDigest: v.optional(v.string()),
    verifierSubject: v.optional(v.string()),
    verdictDigest: v.optional(v.string()),
    createdAt: v.number(),
    expiresAt: v.number(),
    startedAt: v.optional(v.number()),
    evidenceSubmittedAt: v.optional(v.number()),
    verifiedAt: v.optional(v.number()),
    paidAt: v.optional(v.number()),
    terminatedAt: v.optional(v.number()),
    terminationReason: v.optional(v.string()),
  })
    .index("by_workspace_key", ["workspaceId", "idempotencyKey"])
    .index("by_workspace_created", ["workspaceId", "createdAt"])
    .index("by_workspace_state", ["workspaceId", "state"]),

  outcomeEvidenceItems: defineTable({
    workspaceId: v.id("workspaces"),
    outcomeContractId: v.id("outcomeContracts"),
    checkId: v.string(),
    artifactRef: v.string(),
    artifactDigest: v.string(),
    status: v.literal("passed"),
    submittedBy: v.string(),
    createdAt: v.number(),
  }).index("by_contract_check", ["outcomeContractId", "checkId"]),

  outcomeVerdicts: defineTable({
    workspaceId: v.id("workspaces"),
    outcomeContractId: v.id("outcomeContracts"),
    result: v.literal("passed"),
    evidenceDigest: v.string(),
    verdictDigest: v.string(),
    verifierSubject: v.string(),
    createdAt: v.number(),
  }).index("by_contract", ["outcomeContractId"]),

  inferenceBindings: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    mode: v.union(v.literal("inherit-workspace"), v.literal("dedicated")),
    providerConnectionId: v.optional(v.id("providerConnections")),
    providerProfile: v.union(v.literal("economy"), v.literal("balanced"), v.literal("highest-quality")),
    status: v.union(v.literal("ready"), v.literal("setup-required"), v.literal("disabled")),
    updatedAt: v.number(),
  }).index("by_agent", ["agentSpecId"]),

  runtimeAdapters: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    engine: v.union(v.literal("mastra"), v.literal("langgraph"), v.literal("openai-agents"), v.literal("microsoft-agent-framework"), v.literal("google-adk")),
    label: v.string(),
    endpointRef: v.string(),
    secretRef: v.optional(v.string()),
    targetId: v.string(),
    environment: v.union(v.literal("sandbox"), v.literal("production")),
    transport: v.union(v.literal("mastra-native-v1"), v.literal("agent-oven-bridge-v1")),
    status: v.union(v.literal("setup-required"), v.literal("ready"), v.literal("disabled")),
    configDigest: v.string(),
    validationDigest: v.optional(v.string()),
    lastValidatedAt: v.optional(v.number()),
    updatedAt: v.number(),
  })
    .index("by_agent", ["agentSpecId"])
    .index("by_agent_engine", ["agentSpecId", "engine"])
    .index("by_workspace_status", ["workspaceId", "status"]),

  executionJobs: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    blueprintId: v.id("agentBlueprints"),
    blueprintVersion: v.number(),
    creditReservationId: v.optional(v.id("creditReservations")),
    idempotencyKey: v.string(),
    inputRef: v.string(),
    inputDigest: v.string(),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("suspended"), v.literal("succeeded"), v.literal("failed"), v.literal("canceled")),
    runtimePresetVersion: v.optional(v.number()),
    runtimePresetDigest: v.optional(v.string()),
    runtimeAdapterId: v.optional(v.id("runtimeAdapters")),
    runtimeEngine: v.optional(v.union(v.literal("mastra"), v.literal("langgraph"), v.literal("openai-agents"), v.literal("microsoft-agent-framework"), v.literal("google-adk"))),
    runtimeAdapterDigest: v.optional(v.string()),
    quotedRuntimeCredits: v.number(),
    maxAttempts: v.number(),
    attemptCount: v.number(),
    cancellationRequested: v.boolean(),
    resultDigest: v.optional(v.string()),
    failureCode: v.optional(v.string()),
    createdAt: v.number(),
    startedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
  })
    .index("by_workspace_key", ["workspaceId", "idempotencyKey"])
    .index("by_workspace_created", ["workspaceId", "createdAt"])
    .index("by_workspace_status_created", ["workspaceId", "status", "createdAt"]),

  runtimeLeases: defineTable({
    workspaceId: v.id("workspaces"),
    executionJobId: v.id("executionJobs"),
    blueprintId: v.id("agentBlueprints"),
    blueprintVersion: v.number(),
    inputDigest: v.string(),
    state: v.union(v.literal("active"), v.literal("consumed"), v.literal("revoked")),
    workerId: v.optional(v.string()),
    expiresAt: v.number(),
    lastHeartbeatAt: v.optional(v.number()),
    createdAt: v.number(),
  }).index("by_job", ["executionJobId"]),

  executionAttempts: defineTable({
    workspaceId: v.id("workspaces"),
    executionJobId: v.id("executionJobs"),
    attempt: v.number(),
    workerId: v.string(),
    status: v.union(v.literal("running"), v.literal("succeeded"), v.literal("retryable-failure"), v.literal("terminal-failure")),
    failureCode: v.optional(v.string()),
    startedAt: v.number(),
    completedAt: v.optional(v.number()),
  }).index("by_job_attempt", ["executionJobId", "attempt"]),

  runtimeDispatches: defineTable({
    workspaceId: v.id("workspaces"),
    executionJobId: v.id("executionJobs"),
    runtimeAdapterId: v.id("runtimeAdapters"),
    schemaVersion: v.literal("agent-oven.dispatch.v1"),
    transport: v.union(v.literal("mastra-native-v1"), v.literal("agent-oven-bridge-v1")),
    dispatchDigest: v.string(),
    externalRunId: v.optional(v.string()),
    status: v.union(v.literal("prepared"), v.literal("accepted"), v.literal("completed"), v.literal("failed")),
    resultDigest: v.optional(v.string()),
    failureCode: v.optional(v.string()),
    createdAt: v.number(),
    completedAt: v.optional(v.number()),
  }).index("by_job", ["executionJobId"]),

  governedRuntimePresets: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    name: v.string(),
    updateChannel: v.union(v.literal("frozen"), v.literal("managed")),
    maxSteps: v.number(),
    maxInputTokens: v.number(),
    maxOutputTokens: v.number(),
    maxReasoningTokens: v.number(),
    allowedModels: v.array(v.string()),
    allowedTools: v.array(v.string()),
    allowedWorkflows: v.array(v.string()),
    sourceAllowDomains: v.array(v.string()),
    sourceDenyDomains: v.array(v.string()),
    recencyDays: v.optional(v.number()),
    sourceFromDate: v.optional(v.string()),
    sourceToDate: v.optional(v.string()),
    country: v.optional(v.string()),
    region: v.optional(v.string()),
    city: v.optional(v.string()),
    latitude: v.optional(v.number()),
    longitude: v.optional(v.number()),
    radiusKm: v.optional(v.number()),
    requireClarification: v.boolean(),
    rubricVersion: v.string(),
    version: v.number(),
    digest: v.string(),
    status: v.union(v.literal("draft"), v.literal("published")),
    updatedAt: v.number(),
    publishedAt: v.optional(v.number()),
  }).index("by_agent", ["agentSpecId"]),

  governedRuntimePresetVersions: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    presetId: v.id("governedRuntimePresets"),
    version: v.number(),
    canonical: v.string(),
    digest: v.string(),
    createdAt: v.number(),
    publishedAt: v.optional(v.number()),
  }).index("by_preset_version", ["presetId", "version"]),

  runtimeClarifications: defineTable({
    workspaceId: v.id("workspaces"),
    executionJobId: v.id("executionJobs"),
    questionId: v.string(),
    question: v.string(),
    required: v.boolean(),
    answer: v.optional(v.string()),
    answeredBy: v.optional(v.string()),
    createdAt: v.number(),
    answeredAt: v.optional(v.number()),
  }).index("by_job_question", ["executionJobId", "questionId"]),

  runtimeProgressEvents: defineTable({
    workspaceId: v.id("workspaces"),
    executionJobId: v.id("executionJobs"),
    sequence: v.number(),
    phase: v.union(v.literal("plan"), v.literal("gather"), v.literal("sufficiency"), v.literal("synthesize"), v.literal("act"), v.literal("validate"), v.literal("complete")),
    summary: v.string(),
    evidenceClass: v.union(v.literal("declared"), v.literal("observed"), v.literal("verified")),
    createdAt: v.number(),
  }).index("by_job_sequence", ["executionJobId", "sequence"]),

  runtimeFindings: defineTable({
    workspaceId: v.id("workspaces"),
    executionJobId: v.id("executionJobs"),
    title: v.string(),
    summary: v.string(),
    sourceRef: v.optional(v.string()),
    sourceDigest: v.optional(v.string()),
    contradiction: v.boolean(),
    createdAt: v.number(),
  }).index("by_job", ["executionJobId"]),

  runtimeUsageRecords: defineTable({
    workspaceId: v.id("workspaces"),
    executionJobId: v.id("executionJobs"),
    provider: v.string(),
    model: v.string(),
    cachedInputTokens: v.number(),
    inputTokens: v.number(),
    outputTokens: v.number(),
    reasoningTokens: v.number(),
    providerCostMicros: v.number(),
    latencyMs: v.number(),
    toolSteps: v.number(),
    createdAt: v.number(),
  }).index("by_job", ["executionJobId"]),

  runtimeArtifacts: defineTable({
    workspaceId: v.id("workspaces"),
    executionJobId: v.id("executionJobs"),
    label: v.string(),
    objectRef: v.string(),
    digest: v.string(),
    mediaType: v.string(),
    editable: v.boolean(),
    createdAt: v.number(),
  }).index("by_job", ["executionJobId"]),

  runtimeComponentScores: defineTable({
    workspaceId: v.id("workspaces"),
    executionJobId: v.id("executionJobs"),
    component: v.union(v.literal("retrieval"), v.literal("source-selection"), v.literal("planning"), v.literal("synthesis"), v.literal("accuracy"), v.literal("completeness"), v.literal("objectivity"), v.literal("citation-quality"), v.literal("connector-reliability"), v.literal("compliance")),
    method: v.union(v.literal("deterministic"), v.literal("model"), v.literal("statistical")),
    score: v.number(),
    rubricVersion: v.string(),
    evidenceDigest: v.string(),
    createdAt: v.number(),
  }).index("by_job_component", ["executionJobId", "component"]),

  runtimeSnapshots: defineTable({
    workspaceId: v.id("workspaces"),
    executionJobId: v.id("executionJobs"),
    sequence: v.number(),
    currentStepId: v.string(),
    executedPath: v.array(v.string()),
    outputRefs: v.array(v.string()),
    reason: v.string(),
    resumeDigest: v.string(),
    status: v.union(v.literal("suspended"), v.literal("resumed")),
    createdAt: v.number(),
    resumedAt: v.optional(v.number()),
  }).index("by_job_sequence", ["executionJobId", "sequence"]),

  opsManualRules: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    ruleId: v.string(),
    description: v.string(),
    predicate: v.union(v.literal("required-before"), v.literal("forbidden-after"), v.literal("requires-human-gate"), v.literal("max-count")),
    subjectStep: v.string(),
    relatedStep: v.optional(v.string()),
    maxCount: v.optional(v.number()),
    sourceMemoryId: v.optional(v.id("memories")),
    status: v.union(v.literal("draft"), v.literal("published")),
    createdBy: v.string(),
    createdAt: v.number(),
    publishedAt: v.optional(v.number()),
  }).index("by_agent_rule", ["agentSpecId", "ruleId"]),

  databaseToolConnections: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    engine: v.union(v.literal("postgresql"), v.literal("mysql"), v.literal("sql-server"), v.literal("mongodb"), v.literal("warehouse")),
    label: v.string(),
    endpointRef: v.string(),
    secretRef: v.string(),
    allowedNamespaces: v.array(v.string()),
    status: v.union(v.literal("setup-required"), v.literal("active"), v.literal("disabled")),
    validationDigest: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_agent", ["agentSpecId"]),

  databaseToolOperations: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    connectionId: v.id("databaseToolConnections"),
    operationKey: v.string(),
    label: v.string(),
    mode: v.union(v.literal("read"), v.literal("write")),
    executionKind: v.union(v.literal("view"), v.literal("parameterized"), v.literal("stored-procedure")),
    target: v.string(),
    parameterNames: v.array(v.string()),
    approvalRequired: v.boolean(),
    status: v.union(v.literal("draft"), v.literal("published")),
    updatedAt: v.number(),
  }).index("by_connection_key", ["connectionId", "operationKey"]),

  databaseOperationRequests: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    operationId: v.id("databaseToolOperations"),
    parametersDigest: v.string(),
    parametersRef: v.string(),
    requestedBy: v.string(),
    status: v.union(v.literal("awaiting-approval"), v.literal("queued"), v.literal("succeeded"), v.literal("failed"), v.literal("rejected")),
    approvalDigest: v.optional(v.string()),
    approvedBy: v.optional(v.string()),
    resultDigest: v.optional(v.string()),
    failureCode: v.optional(v.string()),
    createdAt: v.number(),
    decidedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
  }).index("by_agent_created", ["agentSpecId", "createdAt"]),

  recipeStudies: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    name: v.string(),
    useCase: v.string(),
    evaluationSetRef: v.string(),
    evaluationSetDigest: v.string(),
    trialCount: v.number(),
    studyCredits: v.number(),
    trialCredits: v.number(),
    spentCredits: v.number(),
    graceCheckpointCount: v.number(),
    pruneFloor: v.number(),
    minQuality: v.number(),
    maxLatencyMs: v.number(),
    qualityWeight: v.number(),
    costWeight: v.number(),
    latencyWeight: v.number(),
    modelCandidates: v.array(v.string()),
    retrievalCandidates: v.array(v.number()),
    memoryCandidates: v.array(v.union(v.literal("none"), v.literal("run-only"), v.literal("governed"))),
    authorityCandidates: v.array(v.union(v.literal("read-only"), v.literal("propose"), v.literal("approval-required"))),
    status: v.union(v.literal("draft"), v.literal("running"), v.literal("review"), v.literal("approved"), v.literal("canceled")),
    creatorId: v.string(),
    championTrialId: v.optional(v.id("recipeTrials")),
    championDigest: v.optional(v.string()),
    frontierDigests: v.optional(v.array(v.string())),
    createdAt: v.number(),
    startedAt: v.optional(v.number()),
    finalizedAt: v.optional(v.number()),
    approvedAt: v.optional(v.number()),
  })
    .index("by_agent_created", ["agentSpecId", "createdAt"])
    .index("by_workspace_status", ["workspaceId", "status"]),

  recipeTrials: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    studyId: v.id("recipeStudies"),
    trialNumber: v.number(),
    model: v.string(),
    retrievalTopK: v.number(),
    memoryMode: v.union(v.literal("none"), v.literal("run-only"), v.literal("governed")),
    authorityMode: v.union(v.literal("read-only"), v.literal("propose"), v.literal("approval-required")),
    recipeDigest: v.string(),
    state: v.union(v.literal("queued"), v.literal("running"), v.literal("pruned"), v.literal("completed"), v.literal("failed")),
    claimedBy: v.optional(v.string()),
    qualityScore: v.optional(v.number()),
    costCredits: v.optional(v.number()),
    latencyMs: v.optional(v.number()),
    policyViolations: v.optional(v.number()),
    eligible: v.optional(v.boolean()),
    pruneReason: v.optional(v.string()),
    evidenceDigest: v.optional(v.string()),
    createdAt: v.number(),
    startedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
  })
    .index("by_study_number", ["studyId", "trialNumber"])
    .index("by_study_state", ["studyId", "state"]),

  recipeCheckpoints: defineTable({
    workspaceId: v.id("workspaces"),
    studyId: v.id("recipeStudies"),
    trialId: v.id("recipeTrials"),
    checkpointNumber: v.number(),
    qualityScore: v.number(),
    cumulativeCredits: v.number(),
    cumulativeLatencyMs: v.number(),
    policyViolations: v.number(),
    createdAt: v.number(),
  }).index("by_trial_checkpoint", ["trialId", "checkpointNumber"]),

  recipePromotions: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    studyId: v.id("recipeStudies"),
    trialId: v.id("recipeTrials"),
    recipeDigest: v.string(),
    status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected")),
    requestedBy: v.string(),
    approvedBy: v.optional(v.string()),
    createdAt: v.number(),
    decidedAt: v.optional(v.number()),
  }).index("by_study", ["studyId"]),

  backupSnapshots: defineTable({
    workspaceId: v.id("workspaces"),
    objectRef: v.string(),
    state: v.union(v.literal("requested"), v.literal("completed"), v.literal("failed")),
    schemaVersion: v.string(),
    recordCount: v.optional(v.number()),
    manifestDigest: v.optional(v.string()),
    failureCode: v.optional(v.string()),
    requestedAt: v.number(),
    completedAt: v.optional(v.number()),
  }).index("by_workspace_requested", ["workspaceId", "requestedAt"]),

  restoreDrills: defineTable({
    workspaceId: v.id("workspaces"),
    backupSnapshotId: v.id("backupSnapshots"),
    targetEnvironment: v.string(),
    state: v.union(v.literal("requested"), v.literal("passed"), v.literal("failed")),
    rowCountMatched: v.optional(v.boolean()),
    receiptChainVerified: v.optional(v.boolean()),
    tenantIsolationVerified: v.optional(v.boolean()),
    rtoSeconds: v.optional(v.number()),
    rpoSeconds: v.optional(v.number()),
    requestedAt: v.number(),
    completedAt: v.optional(v.number()),
  }).index("by_workspace_requested", ["workspaceId", "requestedAt"]),

  releaseCandidates: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    targetVersion: v.number(),
    status: v.union(v.literal("active"), v.literal("promoted"), v.literal("rolled-back")),
    deterministicGatesPassed: v.number(),
    modelScore: v.number(),
    trafficPercent: v.number(),
    observations: v.number(),
    failures: v.number(),
    reason: v.string(),
    createdAt: v.number(),
    completedAt: v.optional(v.number()),
  })
    .index("by_agent_status", ["agentSpecId", "status"])
    .index("by_workspace_created", ["workspaceId", "createdAt"]),

  incidents: defineTable({
    workspaceId: v.id("workspaces"),
    agentSpecId: v.id("agentSpecs"),
    severity: v.union(v.literal("sev1"), v.literal("sev2")),
    status: v.union(v.literal("contained"), v.literal("resolved")),
    summary: v.string(),
    closedRuns: v.number(),
    closedApprovals: v.number(),
    rolledBackCanaries: v.number(),
    resumeEligible: v.boolean(),
    openedAt: v.number(),
    resolvedAt: v.optional(v.number()),
    resolutionNote: v.optional(v.string()),
  })
    .index("by_agent_status", ["agentSpecId", "status"])
    .index("by_workspace_opened", ["workspaceId", "openedAt"]),

  incidentChecks: defineTable({
    workspaceId: v.id("workspaces"),
    incidentId: v.id("incidents"),
    check: v.union(v.literal("containment-verified"), v.literal("evidence-preserved"), v.literal("root-cause-recorded"), v.literal("rollback-verified"), v.literal("owner-approved")),
    completedBy: v.string(),
    completedAt: v.number(),
  }).index("by_incident_check", ["incidentId", "check"]),

  auditEvents: defineTable({
    workspaceId: v.id("workspaces"),
    actor: v.string(),
    event: v.string(),
    targetType: v.string(),
    targetId: v.string(),
    detail: v.string(),
    createdAt: v.number(),
  }).index("by_workspace_created", ["workspaceId", "createdAt"]),
});
